### ISSUE TITLE
why not use nakama 

### ISSUE THREAD

**Issue by diybl** [Raccoons-Rise-Up/client-godot#76]
may be the server use namaka would more fast develop.

**Comment by valkyrienyanko** [comment]
https://heroiclabs.com/pricing/ Namaka is not free.

Also please refer to https://github.com/GodotModules as RRU has been put on hold. If RRU is ever done again it will be done from scratch as I've learned so much from the Godot Modules project.

**Comment by diybl** [comment]
nakam is opensource, you can deploy to your owner server .
https://heroiclabs.com/pricing/  this link is there server's price not the code price.

**Comment by diybl** [comment]
> 


nakam is opensource, you can deploy to your owner server .
https://heroiclabs.com/pricing/ this link is there server's price not the code price.

**Comment by valkyrienyanko** [comment]
Have you ever heard of Mongodb? I've been learning that recently. Is this any better than that?

**Comment by valkyrienyanko** [comment]
I need to know how many bytes are being sent when using this method https://heroiclabs.com/docs/nakama/client-libraries/godot/#binary

![image](https://user-images.githubusercontent.com/6277739/170807330-b0cc9a32-4bc2-4aab-8bc4-41467398b655.png)

The way I have it setup right now with ENet-CSharp, I have full control over the number of bytes I can send.

**Comment by valkyrienyanko** [comment]
There documentation for C# seems very parse. All I can find is a little bit of C# code on the README.md for the Godot repo.

**Comment by valkyrienyanko** [comment]
ENet-CSharp seems to have everything I could ever want. So I'll be sticking with that.

**Comment by diybl** [comment]
nakama can only support single server . it is a fake opensource project

**Comment by valkyrienyanko** [comment]
oh? lol
