### ISSUE TITLE
Can this work for Godot 4+ games with multiplayer and open world chunks?

### ISSUE THREAD

**Issue by WithinAmnesia** [Raccoons-Rise-Up/client-godot#77]
Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET.

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback.

**Comment by valkyrienyanko** [comment]
You have opened up the same issue in ~100 some other projects. My project doesn't even relate to what you're asking. I'm not even going to bother explaining-- I'm closing this...

![Untitled](https://github.com/Raccoons-Rise-Up/client-godot/assets/6277739/ec176931-952e-43f7-8bed-c27be8b8eb6c)
